version: '3'
services:
  node1:
    image: ubuntu:latest
    command: tail -f /dev/null
    working_dir: /root
    volumes:
      - ./config.sh:/root/config/config.sh
      - ./sources.list:/root/config/sources.list